import { test, describe, before, after, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import net from 'node:net';
import http from 'node:http';
import os from 'node:os';
import path from 'node:path';
import fs from 'node:fs';

import { startServer, shutdownServer } from '../../core/server.js';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function getFreePort() {
    return new Promise((resolve, reject) => {
        const srv = net.createServer();
        srv.listen(0, () => {
            const { port } = srv.address();
            srv.close(() => resolve(port));
        });
        srv.on('error', reject);
    });
}

const silentLogger = { info: () => { }, warn: () => { }, error: () => { } };

// Real config shape, per nexus.config.json:
//   backends is an OBJECT keyed by pool name -> array of {url, weight}
//   routes is an array of {path, backend: <pool name>}
function minimalConfig(overrides = {}) {
    return {
        listen: { http: null, https: null },
        logging: { level: 'silent' },
        backends: {},
        routes: [],
        healthcheck: { path: '/health', intervalMs: 60_000, unhealthyThreshold: 3, healthyThreshold: 2 },
        ratelimit: { windowMs: 60_000, maxRequests: 1000, burst: 0 },
        auth: { headerName: 'X-API-Key', keys: [], requiredByDefault: false },
        wal: { enabled: false },
        dashboard: { enabled: false },
        tls: { certPath: null, keyPath: null, sni: false },
        ...overrides
    };
}

function get(port, urlPath = '/') {
    return new Promise((resolve, reject) => {
        http.get({ host: '127.0.0.1', port, path: urlPath, timeout: 2000 }, (res) => {
            let data = '';
            res.on('data', (c) => (data += c));
            res.on('end', () => resolve({ status: res.statusCode, headers: res.headers, body: data }));
        }).on('error', reject);
    });
}

afterEach(async () => {
    await shutdownServer();
});

// ---------------------------------------------------------------------------
// Unit-level: guard conditions
// ---------------------------------------------------------------------------

describe('startServer - guard conditions', () => {
    test('throws if called twice without shutdownServer()', async () => {
        const port = await getFreePort();
        const config = minimalConfig({ listen: { http: port, https: null } });

        await startServer(config, silentLogger);

        await assert.rejects(
            () => startServer(config, silentLogger),
            /already been called|shutdownServer/i
        );
    });

    test('can restart after shutdownServer() resets state', async () => {
        const port = await getFreePort();
        const config = minimalConfig({ listen: { http: port, https: null } });

        await startServer(config, silentLogger);
        await shutdownServer();

        await assert.doesNotReject(() => startServer(config, silentLogger));
    });
});

// ---------------------------------------------------------------------------
// Unit-level: HTTP / HTTPS combinations
// ---------------------------------------------------------------------------

describe('startServer - HTTP/HTTPS combinations', () => {
    test('starts HTTP only when https is null', async () => {
        const port = await getFreePort();
        const config = minimalConfig({ listen: { http: port, https: null } });

        const result = await startServer(config, silentLogger);

        assert.ok(result.httpServer, 'httpServer should be created');
        assert.equal(result.httpsServer, null, 'httpsServer should stay null');
    });

    test('starts neither when both listen ports are null', async () => {
        const config = minimalConfig({ listen: { http: null, https: null } });

        const result = await startServer(config, silentLogger);

        assert.equal(result.httpServer, null);
        assert.equal(result.httpsServer, null);
    });

    test('starts HTTPS via self-signed cert auto-generation (tls.js ensureCertificate)', async () => {
        const httpsPort = await getFreePort();
        const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'nexus-tls-'));
        const certPath = path.join(tmpDir, 'cert.pem');
        const keyPath = path.join(tmpDir, 'key.pem');

        const config = minimalConfig({
            listen: { http: null, https: httpsPort },
            tls: { certPath, keyPath, sni: false }
        });

        const result = await startServer(config, silentLogger);

        assert.ok(result.httpsServer, 'httpsServer should be created');
        assert.ok(fs.existsSync(certPath), 'cert should be auto-generated by tls.js');
        assert.ok(fs.existsSync(keyPath), 'key should be auto-generated by tls.js');
    });

    test('starts both HTTP and HTTPS concurrently', async () => {
        const httpPort = await getFreePort();
        const httpsPort = await getFreePort();
        const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'nexus-tls-'));

        const config = minimalConfig({
            listen: { http: httpPort, https: httpsPort },
            tls: { certPath: path.join(tmpDir, 'cert.pem'), keyPath: path.join(tmpDir, 'key.pem'), sni: false }
        });

        const result = await startServer(config, silentLogger);

        assert.ok(result.httpServer);
        assert.ok(result.httpsServer);
    });
});

// ---------------------------------------------------------------------------
// Unit-level: subsystem wiring
// ---------------------------------------------------------------------------

describe('startServer - subsystem wiring', () => {
    test('does not create wal when config.wal.enabled is false', async () => {
        const port = await getFreePort();
        const config = minimalConfig({ listen: { http: port, https: null }, wal: { enabled: false } });

        const result = await startServer(config, silentLogger);

        assert.equal(result.wal, null);
    });

    test('creates wal when config.wal.enabled is true', async () => {
        const port = await getFreePort();
        const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'nexus-wal-'));

        const config = minimalConfig({
            listen: { http: port, https: null },
            wal: {
                enabled: true,
                path: tmpDir,
                flushIntervalMs: 1000,
                maxFileSizeBytes: 10_485_760,
                retainFiles: 5
            }
        });

        const result = await startServer(config, silentLogger);

        assert.ok(result.wal, 'wal instance should exist');
    });

    test('does not create dashboard when disabled', async () => {
        const port = await getFreePort();
        const config = minimalConfig({ listen: { http: port, https: null }, dashboard: { enabled: false } });

        const result = await startServer(config, silentLogger);

        assert.equal(result.dashboard, null);
    });

    test('creates dashboard when enabled', async () => {
        const port = await getFreePort();
        const config = minimalConfig({
            listen: { http: port, https: null },
            dashboard: { enabled: true, path: '/nexus/dashboard', pushIntervalMs: 2000 }
        });

        const result = await startServer(config, silentLogger);

        assert.ok(result.dashboard, 'dashboard instance should exist');
    });

    test('sets keepAlive on global http agent after boot', async () => {
        const port = await getFreePort();
        const config = minimalConfig({ listen: { http: port, https: null } });

        await startServer(config, silentLogger);

        assert.equal(http.globalAgent.keepAlive, true);
    });

    test('healthChecker stop() is idempotent (proves start() armed a timer)', async () => {
        const port = await getFreePort();
        const config = minimalConfig({ listen: { http: port, https: null } });

        const result = await startServer(config, silentLogger);

        assert.doesNotThrow(() => result.healthChecker.stop());
        assert.doesNotThrow(() => result.healthChecker.stop());
    });
});

// ---------------------------------------------------------------------------
// Unit-level: failure / rollback path
// ---------------------------------------------------------------------------

describe('startServer - failure / rollback path', () => {
    test('rejects and cleans up when HTTP port is already in use', async () => {
        const port = await getFreePort();

        const blocker = http.createServer();
        await new Promise((resolve) => blocker.listen(port, resolve));

        try {
            const config = minimalConfig({ listen: { http: port, https: null } });

            await assert.rejects(
                () => startServer(config, silentLogger),
                /EADDRINUSE/
            );

            const freePort = await getFreePort();
            const retryConfig = minimalConfig({ listen: { http: freePort, https: null } });
            await assert.doesNotReject(() => startServer(retryConfig, silentLogger));
        } finally {
            await new Promise((resolve) => blocker.close(resolve));
        }
    });
});

// ---------------------------------------------------------------------------
// Unit-level: shutdownServer
// ---------------------------------------------------------------------------

describe('shutdownServer', () => {
    test('no-ops safely when nothing was started', async () => {
        await assert.doesNotReject(() => shutdownServer());
    });

    test('closes http server so further connections are refused', async () => {
        const port = await getFreePort();
        const config = minimalConfig({ listen: { http: port, https: null } });

        await startServer(config, silentLogger);
        await shutdownServer();

        // request to 127.0.0.1, not 'localhost' — avoids dual-stack happy-eyeballs
        // AggregateError on platforms (macOS) that try ::1 and 127.0.0.1 both.
        await assert.rejects(
            () => new Promise((resolve, reject) => {
                const req = http.request({ host: '127.0.0.1', port, timeout: 500 }, resolve);
                req.on('error', reject);
                req.end();
            }),
            (err) => {
                if (err.code === 'ECONNREFUSED') return true;
                if (err.name === 'AggregateError') {
                    return err.errors?.some((e) => e.code === 'ECONNREFUSED');
                }
                return false;
            }
        );
    });
});

// ---------------------------------------------------------------------------
// Integration: real request through the full pipeline
// (rateLimit -> routeMatch -> auth -> backendPhase -> forwardToBackend)
// ---------------------------------------------------------------------------

describe('integration: full request lifecycle', () => {
    let backend;
    let backendPort;

    before(async () => {
        backend = http.createServer((req, res) => {
            res.writeHead(200, { 'content-type': 'application/json' });
            res.end(JSON.stringify({ ok: true, path: req.url }));
        });
        backendPort = await getFreePort();
        await new Promise((resolve) => backend.listen(backendPort, resolve));
    });

    after(async () => {
        await new Promise((resolve) => backend.close(resolve));
    });

    test('proxies an HTTP request end-to-end through startServer()', async () => {
        const gatewayPort = await getFreePort();
        const config = minimalConfig({
            listen: { http: gatewayPort, https: null },
            backends: { web: [{ url: `http://127.0.0.1:${backendPort}`, weight: 1 }] },
            routes: [{ path: '/', backend: 'web' }]
        });

        await startServer(config, silentLogger);

        const res = await get(gatewayPort, '/anything');

        assert.equal(res.status, 200);
        const parsed = JSON.parse(res.body);
        assert.equal(parsed.ok, true);
    });

    test('returns 404 for unmatched route', async () => {
        const gatewayPort = await getFreePort();
        const config = minimalConfig({
            listen: { http: gatewayPort, https: null },
            backends: { web: [{ url: `http://127.0.0.1:${backendPort}`, weight: 1 }] },
            routes: [{ path: '/only-this', backend: 'web' }]
        });

        await startServer(config, silentLogger);

        const res = await get(gatewayPort, '/nope');

        assert.equal(res.status, 404);
    });

    test('returns 401 when route requires auth and no key given', async () => {
        const gatewayPort = await getFreePort();
        const config = minimalConfig({
            listen: { http: gatewayPort, https: null },
            backends: { web: [{ url: `http://127.0.0.1:${backendPort}`, weight: 1 }] },
            routes: [{ path: '/', backend: 'web', auth: true }],
            auth: { headerName: 'X-API-Key', keys: ['secret-123'], requiredByDefault: false }
        });

        await startServer(config, silentLogger);

        const res = await get(gatewayPort, '/protected');

        assert.equal(res.status, 401);
    });

    test('returns 502 when route points at a pool with no backends', async () => {
        const gatewayPort = await getFreePort();
        const config = minimalConfig({
            listen: { http: gatewayPort, https: null },
            backends: { web: [] },
            routes: [{ path: '/', backend: 'web' }]
        });

        await startServer(config, silentLogger);

        const res = await get(gatewayPort, '/anything');

        assert.equal(res.status, 502);
    });

    test('returns 429 once rate limit is exhausted', async () => {
        const gatewayPort = await getFreePort();
        const config = minimalConfig({
            listen: { http: gatewayPort, https: null },
            backends: { web: [{ url: `http://127.0.0.1:${backendPort}`, weight: 1 }] },
            routes: [{ path: '/', backend: 'web' }],
            ratelimit: { windowMs: 60_000, maxRequests: 2, burst: 0 }
        });

        await startServer(config, silentLogger);

        const results = [];
        for (let i = 0; i < 4; i++) {
            results.push((await get(gatewayPort, '/x')).status);
        }

        assert.ok(results.includes(429), `expected a 429 among ${results}`);
    });

    test('gateway responds correctly across N sequential requests (keepAlive sanity)', async () => {
        const gatewayPort = await getFreePort();
        const config = minimalConfig({
            listen: { http: gatewayPort, https: null },
            backends: { web: [{ url: `http://127.0.0.1:${backendPort}`, weight: 1 }] },
            routes: [{ path: '/', backend: 'web' }]
        });

        await startServer(config, silentLogger);

        for (let i = 0; i < 5; i++) {
            const res = await get(gatewayPort, `/req-${i}`);
            assert.equal(res.status, 200);
        }
    });

    test('shutdownServer() completes well within the shutdown timeout when idle', async () => {
        const gatewayPort = await getFreePort();
        const config = minimalConfig({
            listen: { http: gatewayPort, https: null },
            backends: { web: [{ url: `http://127.0.0.1:${backendPort}`, weight: 1 }] },
            routes: [{ path: '/', backend: 'web' }]
        });

        await startServer(config, silentLogger, { shutdownTimeoutMs: 2000 });

        const start = Date.now();
        await shutdownServer();
        const elapsed = Date.now() - start;

        assert.ok(elapsed < 2000, `shutdown took ${elapsed}ms, expected fast graceful close`);
    });
});